name: Tests

on:
  push: ~
  pull_request: ~

jobs:
  pytest:
    name: Python on ${{ matrix.python }} and Sphinx ${{ matrix.sphinx }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ 3.6, 3.7, 3.8, 3.9 ]
        sphinx: [ 1.*, 2.*, 3.*, 4.* ]
    steps:
      - name: Update code
        uses: actions/checkout@v2
      - name: Install dependencies (Sphinx ${{ matrix.sphinx }})
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          SPHINX_VERSION: ${{ matrix.sphinx }}
        run: |
          ./run init
          ./run deps
      - name: Run tests
        env:
          PYTHON_VERSION: ${{ matrix.python }}
        run: ./run tests
